runtime: python27
api_version: 1
threadsafe: true

default_expiration: "3s"

handlers:
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html

- url: /api.*
  script: main.app

- url: (.*)
  static_files: frontend\1
  upload: frontend/(.*)