runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "3s"

handlers:
- url: /api.*
  script: main.app

- url: (.*)/
  static_files: client/index.html
  upload: client/index.html

- url: (.*)
  static_files: client\1
  upload: client/(.*)