runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /api/instituicao
  script: main.app
  

- url: /api/usuario
  script: main.app
  

- url: /api/posts
  script: main.app
  

- url: /
  static_files: app/index.html
  upload: app/index.html
